[frac]
type = "Template"
template = '\frac{$0}{$1}'
args_count = 2
alias = ["f"]

[mat]
type = "Environment"
env_name = "pmatrix"
alias = ["m"]

[lim]
type = "Template"
template = '\lim_{$0 \to $1} $2'
args_count = 2
